name: upload oss

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [8.x, 10.x, 12.x]

    steps:
      #拉取代码
      - name: Checkout
        uses: actions/checkout@master
      - name: setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: cp files to aliyun
        run: ossutil cp -rf ./ oss://timing-web
